### PR TITLE
Export some handy hexo related global functions to the Sass compiler context like [mamboer/hexo-renderer-scss]

### PR DESCRIPTION
**Pull request by yaohwu**
There are some handy functions in [mamboer/hexo-renderer-scss](https://github.com/mamboer/hexo-renderer-scss) that used by some themes like [ahonn/hexo-theme-even](https://github.com/ahonn/hexo-theme-even)

Just using ts to implement same features and trying to resolve a issue https://github.com/ahonn/hexo-theme-even/issues/285

### CODE REVIEW

**Comment by yaohwu** [comment]
@KentarouTakeda

**Review by yaohwu — COMMENTED** [review]
lgtm

**Comment by yaohwu** [comment]
Is there any questions?

**Review by KentarouTakeda — APPROVED** [review]
@yaohwu Thanks!

**Pull request merged**
